provider: openrouter
openrouter_api_key: ${OPENROUTER_API_KEY}
# anthropic_api_key: ${ANTHROPIC_API_KEY}
# bedrock_region: ${BEDROCK_REGION}
models:
  default: ${DEFAULT_MODEL}
  pro: ${PRO_MODEL}
  free: ${FREE_MODEL}
postgres_dsn: ${POSTGRES_DSN}
default_embedding_model: ${DEFAULT_EMBEDDING_MODEL}
default_rerank_model: ${DEFAULT_RERANK_MODEL}
